[build]
  command = "npm run build"
  publish = "_site"

[[headers]]
  # cache-control for the logo (in navs so noticeable)
  for = "/images/logo.png"
  [headers.values]
    cache-control = '''
    max-age=2678400,
    public'''