[build]
  command = "npm run build"
  publish = "_site"
  functions = "functions"

[[headers]]
  # cache-control for the logo (in navs so noticeable)
  for = "*.png"
  [headers.values]
    cache-control = '''
    max-age=2678400,
    public'''

[[headers]]
  # cache-control for the logo (in navs so noticeable)
  for = "*.jpg"
  [headers.values]
    cache-control = '''
    max-age=2678400,
    public'''

[[headers]]
  # cache-control for the logo (in navs so noticeable)
  for = "*.jpeg"
  [headers.values]
    cache-control = '''
    max-age=2678400,
    public'''